CREATE TABLE numid (
  id int(11) NOT NULL AUTO_INCREMENT,
  numC int(11) NOT NULL,
  numB int(11) NOT NULL,
  UNIQUE INDEX id (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;