CREATE TABLE IF NOT EXISTS registry_zayvki(
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  id_zayvki INT(11) UNSIGNED NOT NULL,
  `data` DATETIME NOT NULL,
  summa DOUBLE NOT NULL,
  payIn VARCHAR(255) NOT NULL,
  fioClient VARCHAR(255) NOT NULL,
  mailClient VARCHAR(255) NOT NULL,
  payOut VARCHAR(255) NOT NULL,
  UNIQUE INDEX id (id),
  UNIQUE INDEX id_zayvki (id_zayvki)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;